### PR TITLE
display the content of an object variable

### PR DESCRIPTION
**Pull request by IdanAizikNissim**
https://glitch.com/edit/#!/assorted-physician

Bind object in var attribute
example:
var person = {name: 'idan', address: {city:'tel-aviv'}};
<p var="person.name"></p>
<p var="person.address.city"></p>

### CODE REVIEW

**Comment by arguiot** [comment]
Travis isn't building correctly DislayJS, fix it please 😊

**Comment by IdanAizikNissim** [comment]
Oh thx 😄,  arrrrr spaces 🙃

**Comment by arguiot** [comment]
I fixed it 😊

**Comment by arguiot** [comment]
Don't forget to leave a star 🌟

**Pull request merged**
